package rs.imlek.lorascore;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.view.*;import android.view.inputmethod.*;import android.widget.*;import java.text.*;import java.util.*;

public class MainActivity extends Activity{
  String[] games={"Plus","Minus","Pop Herc","Dame","Herčevi","Lora","Igra po želji"};
  EditText[] names=new EditText[4], inputs=new EditText[4]; TextView title,total,rank; LinearLayout root; SharedPreferences sp; int round=0, game=0; int[][][] scores=new int[4][7][4];
  int bg=Color.rgb(17,24,39), card=Color.rgb(31,41,55), txt=Color.WHITE, accent=Color.rgb(34,197,94);
  public void onCreate(Bundle b){super.onCreate(b);sp=getSharedPreferences("lora",0);load(); if(emptyNames()) setup(); else gameScreen();}
  TextView tv(String s,int size,int style){TextView v=new TextView(this);v.setText(s);v.setTextColor(txt);v.setTextSize(size);v.setTypeface(Typeface.DEFAULT,style);v.setPadding(12,8,12,8);return v;}
  Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextSize(16);b.setAllCaps(false);return b;}
  EditText et(String hint){EditText e=new EditText(this);e.setHint(hint);e.setTextColor(txt);e.setHintTextColor(Color.LTGRAY);e.setTextSize(18);e.setSingleLine(true);e.setInputType(android.text.InputType.TYPE_CLASS_NUMBER|android.text.InputType.TYPE_NUMBER_FLAG_SIGNED);e.setPadding(18,8,18,8);return e;}
  void base(){ScrollView sv=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(20,24,20,24);root.setBackgroundColor(bg);sv.addView(root);setContentView(sv);} 
  boolean emptyNames(){for(int i=0;i<4;i++) if(sp.getString("n"+i,"").length()>0) return false; return true;}
  void setup(){base();root.addView(tv("🂡 Lora Score",30,Typeface.BOLD));root.addView(tv("Unesi imena 4 igrača",18,Typeface.NORMAL));for(int i=0;i<4;i++){names[i]=et("Igrač "+(i+1));names[i].setInputType(android.text.InputType.TYPE_CLASS_TEXT);names[i].setText(sp.getString("n"+i,""));root.addView(names[i]);}Button start=btn("Počni partiju");root.addView(start);start.setOnClickListener(v->{for(int i=0;i<4;i++){String n=names[i].getText().toString().trim();sp.edit().putString("n"+i,n.length()>0?n:"Igrač "+(i+1)).apply();}save();gameScreen();});}
  void gameScreen(){base();title=tv("",26,Typeface.BOLD);root.addView(title); LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.VERTICAL);row.setBackgroundColor(card);row.setPadding(10,10,10,10);root.addView(row); for(int i=0;i<4;i++){TextView l=tv(sp.getString("n"+i,"Igrač "+(i+1)),16,Typeface.BOLD);inputs[i]=et("0");inputs[i].setText(val(round,game,i));row.addView(l);row.addView(inputs[i]); final int ix=i; inputs[i].setOnFocusChangeListener((v,h)->{if(!h) storeInputs();});}
    Button next=btn("Sledeća igra");Button prev=btn("Prethodna");Button finish=btn("Završi partiju");Button clear=btn("Obriši sve");Button rename=btn("Promeni imena");root.addView(next);root.addView(prev);root.addView(finish);root.addView(clear);root.addView(rename);total=tv("",20,Typeface.BOLD);rank=tv("",18,Typeface.NORMAL);root.addView(total);root.addView(rank); refresh(); next.setOnClickListener(v->{storeInputs(); if(game<6)game++; else if(round<3){round++;game=0;} refresh();}); prev.setOnClickListener(v->{storeInputs(); if(game>0)game--; else if(round>0){round--;game=6;} refresh();}); finish.setOnClickListener(v->{storeInputs();saveHistory();Toast.makeText(this,"Partija sačuvana",Toast.LENGTH_LONG).show();}); clear.setOnClickListener(v->confirmClear()); rename.setOnClickListener(v->setup());}
  String val(int r,int g,int p){int x=scores[r][g][p];return x==0?"":String.valueOf(x);} 
  void storeInputs(){for(int i=0;i<4;i++){try{String s=inputs[i].getText().toString().trim();scores[round][game][i]=s.length()==0?0:Integer.parseInt(s);}catch(Exception e){scores[round][game][i]=0;}}save();}
  void refresh(){title.setText("Partija "+(round+1)+" / 4  •  "+games[game]);for(int i=0;i<4;i++)inputs[i].setText(val(round,game,i)); int[] t=totals();StringBuilder sb=new StringBuilder("Total score\n");for(int i=0;i<4;i++)sb.append(sp.getString("n"+i,"Igrač "+(i+1))).append(": ").append(t[i]).append("\n");total.setText(sb.toString());rank.setText(ranking(t));}
  int[] totals(){int[] t=new int[4];for(int r=0;r<4;r++)for(int g=0;g<7;g++)for(int p=0;p<4;p++)t[p]+=scores[r][g][p];return t;}
  String ranking(int[] t){Integer[] idx={0,1,2,3};Arrays.sort(idx,(a,b)->Integer.compare(t[a],t[b]));String[] med={"🥇","🥈","🥉","4."};StringBuilder sb=new StringBuilder("Rang lista (najmanji rezultat pobeđuje)\n");for(int k=0;k<4;k++){int i=idx[k];sb.append(med[k]).append(" ").append(sp.getString("n"+i,"Igrač "+(i+1))).append(" — ").append(t[i]).append("\n");}return sb.toString();}
  void confirmClear(){new AlertDialog.Builder(this).setTitle("Obriši sve?").setMessage("Brišu se svi rezultati, imena ostaju.").setPositiveButton("Obriši",(d,w)->{scores=new int[4][7][4];round=0;game=0;save();gameScreen();}).setNegativeButton("Otkaži",null).show();}
  void save(){SharedPreferences.Editor e=sp.edit();e.putInt("round",round);e.putInt("game",game);for(int r=0;r<4;r++)for(int g=0;g<7;g++)for(int p=0;p<4;p++)e.putInt("s"+r+g+p,scores[r][g][p]);e.apply();}
  void load(){round=sp.getInt("round",0);game=sp.getInt("game",0);for(int r=0;r<4;r++)for(int g=0;g<7;g++)for(int p=0;p<4;p++)scores[r][g][p]=sp.getInt("s"+r+g+p,0);} 
  void saveHistory(){int[] t=totals();String rec=new SimpleDateFormat("dd.MM.yyyy HH:mm",Locale.getDefault()).format(new Date())+"\n"+ranking(t);String old=sp.getString("history","");sp.edit().putString("history",rec+"\n---\n"+old).apply();}
}
