package rs.imlek.lorascore;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.view.*;import android.view.inputmethod.InputMethodManager;import android.widget.*;import java.text.*;import java.util.*;

public class MainActivity extends Activity{
 int rounds=4, gamesN=7, playersN=4, current=0; String[] games={"Plus","Minus","Pop Herc","Dame","Herčevi","Lora","Igra po želji"};
 String[] players={"Igrač 1","Igrač 2","Igrač 3","Igrač 4"}; int[][][] scores=new int[4][7][4];
 LinearLayout root, scoreInputs, totalsBox, historyBox; TextView currentTitle, progress, winner; EditText[] nameInputs=new EditText[4], scoreEdits=new EditText[4]; SharedPreferences sp; boolean loading=false;
 int bg=Color.rgb(17,24,39), card=Color.rgb(31,41,55), text=Color.WHITE, muted=Color.rgb(209,213,219), green=Color.rgb(34,197,94), red=Color.rgb(248,113,113);
 @Override public void onCreate(Bundle b){super.onCreate(b);sp=getSharedPreferences("lora",0);load();build();render();}
 TextView tv(String s,int size,int color,int style){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(color);v.setTypeface(Typeface.DEFAULT,style);v.setPadding(12,8,12,8);return v;}
 EditText edit(String s){EditText e=new EditText(this);e.setText(s);e.setTextColor(text);e.setTextSize(16);e.setSingleLine(true);e.setSelectAllOnFocus(true);e.setPadding(18,10,18,10);e.setBackgroundColor(Color.rgb(55,65,81));return e;}
 Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(15);return b;}
 LinearLayout box(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(14,14,14,14);l.setBackgroundColor(card);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(10,8,10,8);l.setLayoutParams(p);return l;}
 public void build(){ScrollView sv=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(10,18,10,30);root.setBackgroundColor(bg);sv.addView(root);setContentView(sv);
  TextView title=tv("♠ Lora Score",30,text,Typeface.BOLD);root.addView(title);root.addView(tv("Pobednik je igrač sa najmanjim ukupnim brojem poena. Poeni mogu biti i negativni.",14,muted,Typeface.NORMAL));
  LinearLayout names=box();names.addView(tv("Igrači",20,text,Typeface.BOLD));for(int i=0;i<4;i++){nameInputs[i]=edit(players[i]);final int ix=i;nameInputs[i].setOnFocusChangeListener((v,h)->{if(!h){players[ix]=nameInputs[ix].getText().toString().trim().length()==0?"Igrač "+(ix+1):nameInputs[ix].getText().toString().trim();save();renderTotals();}});names.addView(nameInputs[i]);}root.addView(names);
  LinearLayout game=box();progress=tv("",14,muted,Typeface.BOLD);currentTitle=tv("",24,text,Typeface.BOLD);game.addView(progress);game.addView(currentTitle);scoreInputs=new LinearLayout(this);scoreInputs.setOrientation(LinearLayout.VERTICAL);game.addView(scoreInputs);root.addView(game);
  LinearLayout nav=new LinearLayout(this);nav.setOrientation(LinearLayout.HORIZONTAL);Button prev=btn("Prethodna");Button next=btn("Sledeća igra");Button finish=btn("Završi partiju");prev.setOnClickListener(v->{if(current>0){current--;render();}});next.setOnClickListener(v->{collectScores();if(current<rounds*gamesN-1)current++;save();render();});finish.setOnClickListener(v->{collectScores();finishGame();});nav.addView(prev,new LinearLayout.LayoutParams(0,-2,1));nav.addView(next,new LinearLayout.LayoutParams(0,-2,1));root.addView(nav);root.addView(finish,new LinearLayout.LayoutParams(-1,-2));
  totalsBox=box();root.addView(totalsBox);LinearLayout actions=new LinearLayout(this);actions.setOrientation(LinearLayout.HORIZONTAL);Button reset=btn("Nova partija");Button clear=btn("Obriši sve");reset.setOnClickListener(v->confirm("Nova partija? Imena ostaju, rezultati se brišu.",()->{scores=new int[4][7][4];current=0;save();render();}));clear.setOnClickListener(v->confirm("Obrisati sve rezultate i istoriju?",()->{sp.edit().clear().apply();players=new String[]{"Igrač 1","Igrač 2","Igrač 3","Igrač 4"};scores=new int[4][7][4];current=0;load();render();}));actions.addView(reset,new LinearLayout.LayoutParams(0,-2,1));actions.addView(clear,new LinearLayout.LayoutParams(0,-2,1));root.addView(actions);historyBox=box();root.addView(historyBox);
 }
 void render(){loading=true;int r=current/gamesN,g=current%gamesN;progress.setText("Partija "+(r+1)+" od 4 • Igra "+(g+1)+" od 7");currentTitle.setText(games[g]);scoreInputs.removeAllViews();for(int i=0;i<4;i++){TextView lab=tv(players[i],14,muted,Typeface.BOLD);scoreInputs.addView(lab);scoreEdits[i]=edit(String.valueOf(scores[r][g][i]));scoreEdits[i].setInputType(android.text.InputType.TYPE_CLASS_NUMBER|android.text.InputType.TYPE_NUMBER_FLAG_SIGNED);final int ix=i;scoreEdits[i].setOnFocusChangeListener((v,h)->{if(!h){collectScores();save();renderTotals();}});scoreInputs.addView(scoreEdits[i]);}loading=false;renderTotals();renderHistory();}
 void collectScores(){if(loading)return;int r=current/gamesN,g=current%gamesN;for(int i=0;i<4;i++){try{scores[r][g][i]=Integer.parseInt(scoreEdits[i].getText().toString().trim());}catch(Exception e){scores[r][g][i]=0;}}for(int i=0;i<4;i++){String n=nameInputs[i].getText().toString().trim();players[i]=n.length()==0?"Igrač "+(i+1):n;}}
 int[] totals(){int[] t=new int[4];for(int r=0;r<4;r++)for(int g=0;g<7;g++)for(int p=0;p<4;p++)t[p]+=scores[r][g][p];return t;}
 void renderTotals(){totalsBox.removeAllViews();totalsBox.addView(tv("Total score",22,text,Typeface.BOLD));int[] t=totals();Integer[] idx={0,1,2,3};Arrays.sort(idx,(a,b)->Integer.compare(t[a],t[b]));winner=tv("🏆 Vodi: "+players[idx[0]]+" ("+t[idx[0]]+")",18,green,Typeface.BOLD);totalsBox.addView(winner);for(int pos=0;pos<4;pos++){int i=idx[pos];TextView row=tv((pos+1)+". "+players[i]+"  —  "+t[i]+" poena",17,pos==0?green:text,Typeface.BOLD);totalsBox.addView(row);} }
 void renderHistory(){historyBox.removeAllViews();historyBox.addView(tv("Istorija partija",20,text,Typeface.BOLD));String h=sp.getString("history","");if(h.length()==0){historyBox.addView(tv("Još nema sačuvanih partija.",14,muted,Typeface.NORMAL));return;}String[] lines=h.split("\\n",-1);for(String line:lines)if(line.trim().length()>0)historyBox.addView(tv(line,14,muted,Typeface.NORMAL));}
 void finishGame(){int[] t=totals();Integer[] idx={0,1,2,3};Arrays.sort(idx,(a,b)->Integer.compare(t[a],t[b]));String date=new SimpleDateFormat("dd.MM.yyyy HH:mm",Locale.getDefault()).format(new Date());String line=date+" • Pobednik: "+players[idx[0]]+" ("+t[idx[0]]+")";sp.edit().putString("history",line+"\n"+sp.getString("history","")).apply();save();renderHistory();new AlertDialog.Builder(this).setTitle("Partija završena").setMessage("Pobednik: "+players[idx[0]]+"\nRezultat: "+t[idx[0]]).setPositiveButton("Nova partija",(d,w)->{scores=new int[4][7][4];current=0;save();render();}).setNegativeButton("Ostani",null).show();}
 void confirm(String msg, final Runnable yes){new AlertDialog.Builder(this).setTitle("Potvrda").setMessage(msg).setPositiveButton("Da",(d,w)->yes.run()).setNegativeButton("Ne",null).show();}
 void save(){SharedPreferences.Editor e=sp.edit();e.putInt("current",current);for(int i=0;i<4;i++)e.putString("p"+i,players[i]);for(int r=0;r<4;r++)for(int g=0;g<7;g++)for(int p=0;p<4;p++)e.putInt("s"+r+"_"+g+"_"+p,scores[r][g][p]);e.apply();}
 void load(){current=sp.getInt("current",0);for(int i=0;i<4;i++)players[i]=sp.getString("p"+i,players[i]);for(int r=0;r<4;r++)for(int g=0;g<7;g++)for(int p=0;p<4;p++)scores[r][g][p]=sp.getInt("s"+r+"_"+g+"_"+p,0);}
}
