package rs.lora.score;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.view.*;import android.view.inputmethod.EditorInfo;import android.widget.*;import java.util.*;

public class MainActivity extends Activity{
    final String[] games={"Plus","Minus","Pop Herc","Dame","Herčevi","Lora","Igra po želji"};
    final int players=4, rounds=4; EditText[] names=new EditText[4]; EditText[][][] cells=new EditText[4][7][4]; TextView[] totals=new TextView[4]; TextView ranking; SharedPreferences sp; LinearLayout root;
    int bg=Color.rgb(17,24,39), card=Color.rgb(31,41,55), text=Color.WHITE, muted=Color.rgb(209,213,219), accent=Color.rgb(34,197,94);
    public void onCreate(Bundle b){super.onCreate(b);sp=getSharedPreferences("lora",0);build();load();calc();}
    TextView tv(String s,int size,int style){TextView v=new TextView(this);v.setText(s);v.setTextColor(text);v.setTextSize(size);v.setTypeface(Typeface.DEFAULT,style);v.setPadding(10,8,10,8);return v;}
    EditText et(String hint){EditText e=new EditText(this);e.setHint(hint);e.setTextColor(text);e.setHintTextColor(muted);e.setSingleLine(true);e.setTextSize(16);e.setInputType(android.text.InputType.TYPE_CLASS_NUMBER|android.text.InputType.TYPE_NUMBER_FLAG_SIGNED);e.setImeOptions(EditorInfo.IME_ACTION_NEXT);e.setPadding(10,4,10,4);e.setBackgroundColor(Color.rgb(55,65,81));return e;}
    Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTextSize(14);b.setBackgroundColor(accent);return b;}
    public void build(){ScrollView sc=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(18,18,18,28);root.setBackgroundColor(bg);sc.addView(root);setContentView(sc);
        TextView title=tv("Lora Score",28,Typeface.BOLD);root.addView(title);root.addView(tv("Pobednik je igrač sa najmanje poena. Poeni mogu biti negativni.",14,Typeface.NORMAL));
        LinearLayout nameBox=new LinearLayout(this);nameBox.setOrientation(LinearLayout.VERTICAL);nameBox.setPadding(8,8,8,8);root.addView(nameBox);
        for(int i=0;i<4;i++){names[i]=new EditText(this);names[i].setHint("Igrač "+(i+1));names[i].setTextColor(text);names[i].setHintTextColor(muted);names[i].setSingleLine(true);names[i].setTextSize(17);names[i].setBackgroundColor(card);names[i].setPadding(14,8,14,8); final int idx=i; names[i].addTextChangedListener(new SimpleWatcher(){public void afterTextChanged(android.text.Editable e){save();drawHeaders();calc();}}); nameBox.addView(names[i],new LinearLayout.LayoutParams(-1,-2));}
        for(int r=0;r<rounds;r++){TextView h=tv("Partija "+(r+1),20,Typeface.BOLD);h.setPadding(10,24,10,8);root.addView(h); TableLayout table=new TableLayout(this);table.setStretchAllColumns(true);root.addView(table); addHeader(table); for(int g=0;g<games.length;g++){TableRow row=new TableRow(this); TextView gn=tv(games[g],13,Typeface.BOLD);gn.setTextColor(muted);row.addView(gn); for(int p=0;p<players;p++){EditText c=et("0"); final int rr=r,gg=g,pp=p; c.addTextChangedListener(new SimpleWatcher(){public void afterTextChanged(android.text.Editable e){save();calc();}}); cells[r][g][p]=c; row.addView(c);} table.addView(row);} }
        TextView totalTitle=tv("Total score",22,Typeface.BOLD);totalTitle.setPadding(10,24,10,8);root.addView(totalTitle); LinearLayout totalBox=new LinearLayout(this);totalBox.setOrientation(LinearLayout.VERTICAL);root.addView(totalBox); for(int p=0;p<players;p++){totals[p]=tv("",19,Typeface.BOLD);totals[p].setBackgroundColor(card);totals[p].setPadding(14,10,14,10);totalBox.addView(totals[p],new LinearLayout.LayoutParams(-1,-2));}
        ranking=tv("",18,Typeface.BOLD);ranking.setPadding(14,16,14,16);root.addView(ranking);
        LinearLayout buttons=new LinearLayout(this);buttons.setOrientation(LinearLayout.HORIZONTAL);root.addView(buttons);Button clear=btn("Obriši sve");Button sample=btn("Sačuvaj imena");buttons.addView(clear,new LinearLayout.LayoutParams(0,-2,1));buttons.addView(sample,new LinearLayout.LayoutParams(0,-2,1));
        clear.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("Obriši sve?").setMessage("Svi uneti rezultati biće obrisani.").setPositiveButton("Obriši",(d,w)->{sp.edit().clear().apply();for(EditText n:names)n.setText("");for(int r=0;r<rounds;r++)for(int g=0;g<7;g++)for(int p=0;p<4;p++)cells[r][g][p].setText("");calc();}).setNegativeButton("Otkaži",null).show());
        sample.setOnClickListener(v->{save();Toast.makeText(this,"Sačuvano",Toast.LENGTH_SHORT).show();});
    }
    void addHeader(TableLayout t){TableRow row=new TableRow(this);row.addView(tv("Igra",13,Typeface.BOLD));for(int i=0;i<4;i++)row.addView(tv(name(i),13,Typeface.BOLD));t.addView(row);} void drawHeaders(){}
    String name(int i){String n=names[i]==null?"":names[i].getText().toString().trim();return n.length()>0?n:"Igrač "+(i+1);} int val(EditText e){try{return Integer.parseInt(e.getText().toString().trim());}catch(Exception ex){return 0;}}
    void calc(){int[] sum=new int[4];for(int r=0;r<rounds;r++)for(int g=0;g<7;g++)for(int p=0;p<4;p++)sum[p]+=val(cells[r][g][p]);Integer[] ord={0,1,2,3};Arrays.sort(ord,(a,b)->Integer.compare(sum[a],sum[b]));for(int p=0;p<4;p++){totals[p].setText(name(p)+": "+sum[p]);totals[p].setTextColor(p==ord[0]?accent:text);}StringBuilder sb=new StringBuilder("Rang lista\n");String[] med={"🥇 ","🥈 ","🥉 ","4. "};for(int i=0;i<4;i++)sb.append(med[i]).append(name(ord[i])).append(" — ").append(sum[ord[i]]).append("\n");ranking.setText(sb.toString());}
    void save(){SharedPreferences.Editor e=sp.edit();for(int i=0;i<4;i++)if(names[i]!=null)e.putString("n"+i,names[i].getText().toString());for(int r=0;r<rounds;r++)for(int g=0;g<7;g++)for(int p=0;p<4;p++)if(cells[r][g][p]!=null)e.putString("c"+r+"_"+g+"_"+p,cells[r][g][p].getText().toString());e.apply();}
    void load(){for(int i=0;i<4;i++)names[i].setText(sp.getString("n"+i,""));for(int r=0;r<rounds;r++)for(int g=0;g<7;g++)for(int p=0;p<4;p++)cells[r][g][p].setText(sp.getString("c"+r+"_"+g+"_"+p,""));}
    public static abstract class SimpleWatcher implements android.text.TextWatcher{public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int b,int c){}}
}
